services:
  - type: web
    name: location-scraper-webapp(1)
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: gunicorn -b 0.0.0.0:$PORT location_scraper_webapp(1):app

    envVars:
      - key: PYTHON_VERSION
        value: 3.10
