services:
  - type: web
    name: location-scraper-webapp
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install
    startCommand: gunicorn -b 0.0.0.0:$PORT location_scraper_webapp:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
