services:
  - type: web
    name: location-scraper-webapp
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wget gnupg ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 \
      libatk1.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 libx11-xcb1 libxcomposite1 \
      libxdamage1 libxrandr2 xdg-utils
      pip install -r requirements.txt
      python -m playwright install --with-deps
    startCommand: gunicorn -b 0.0.0.0:$PORT location_scraper_webapp:app
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /tmp/playwright
      - key: PYTHON_VERSION
        value: 3.10
